### ISSUE TITLE
[Bug] Develop branch exhibits ctest failures on Mac arm64 architecture

### ISSUE THREAD

**Issue by srherbener** [JCSDA-internal/ioda-converters#1284]
## Current behavior (describe the bug)

Running ctests for ioda-converters on Mac arm64 (native M1 or M2 architecture) using the develop branch exhibits the following 26 test failures:
```
The following tests FAILED:
	661 - test_iodaconv_bufr_ncep_1bamua2ioda (Failed)
	662 - test_iodaconv_bufr_ncep_1bamua2ioda_n15 (Failed)
	663 - test_iodaconv_bufr_ncep_esamua2ioda (Failed)
	666 - test_iodaconv_bufr_ncep_adpsfc2ioda (Failed)
	667 - test_iodaconv_prepbufr_ncep_adpsfc2ioda (Failed)
	668 - test_iodaconv_bufr_ncep_snowadpsfc2ioda (Failed)
	669 - test_iodaconv_bufr_ncep_aircar2ioda (Failed)
	670 - test_iodaconv_bufr_ncep_aircft_noamdar2ioda (Failed)
	671 - test_iodaconv_bufr_ncep_aircft_amdar2ioda (Failed)
	672 - test_iodaconv_prepbufr_ncep_aircftprofiles2ioda (Failed)
	674 - test_iodaconv_bufr_read_wmo_radiosonde (Failed)
	675 - test_iodaconv_bufr_satwnd_old_format (Failed)
	676 - test_iodaconv_bufr_satwnd_new_format (Failed)
	677 - test_iodaconv_bufr_ncep_satwind_avhrr (Failed)
	678 - test_iodaconv_bufr_ncep_mtiasi (Failed)
	679 - test_iodaconv_bufr_ncep_atms (Failed)
	681 - test_iodaconv_bufr_empty_fields (Failed)
	683 - test_iodaconv_bufr_adpupa (Failed)
	684 - test_iodaconv_bufr_ncep_prepbufr_adpupa (Failed)
	685 - test_iodaconv_bufr_ncep_adpupa2ioda (Failed)
	686 - test_iodaconv_bufr_ncep_mesonet2ioda (Failed)
	690 - test_iodaconv_bufr_ncep_lgycld (Failed)
	691 - test_iodaconv_bufr_ncep_prepbufr_adpsfc_cloud (Failed)
	692 - test_iodaconv_bufr_wmo_amdar_multi (Failed)
	705 - test_iodaconv_mhs_conv (Failed)
	706 - test_iodaconv_amsua_conv (Failed)
Errors while running CTest
```

A quick view of the `Testing/Temporary/LastTest.log` file shows results like this:
```
...
DIFFER : VARIABLE : sensorViewAngle : POSITION : [838] : VALUES : -1.671 <> -1.671
DIFFER : VARIABLE : sensorViewAngle : POSITION : [839] : VALUES : 1.662 <> 1.662
DIFFER : VARIABLE : sensorViewAngle : POSITION : [843] : VALUES : 14.994 <> 14.994
DIFFER : VARIABLE : sensorViewAngle : POSITION : [844] : VALUES : 18.327 <> 18.327
DIFFER : VARIABLE : sensorViewAngle : POSITION : [845] : VALUES : 21.66 <> 21.66
DIFFER : VARIABLE : sensorViewAngle : POSITION : [846] : VALUES : 24.993 <> 24.993
DIFFER : VARIABLE : sensorViewAngle : POSITION : [847] : VALUES : 28.326 <> 28.326
Variable        Group     Count         Sum      AbsSum          Min        Max       Range        Mean      StdDev
sensorViewAngle /MetaData   342 0.000457525 0.000510931 -9.53674e-07 3.8147e-06 4.76837e-06 1.33779e-06 1.13627e-06
<end of output>
Test time =   0.32 sec
----------------------------------------------------------
Test Failed.
"test_iodaconv_bufr_ncep_1bamua2ioda" end time: Jul 03 09:31 MDT
"test_iodaconv_bufr_ncep_1bamua2ioda" time elapsed: 00:00:00
----------------------------------------------------------
```
which seem to suggest that there are slight differences in floating point values and the test failures might be due to tolerances being too tight.

On the one hand, the converters (in general) should just be copying data which should result in exact matches, but perhaps there is something like float -> double -> float conversions in the data flow which could result in tiny changes.

## To Reproduce

> What computer are you running on?

MacOS, Ventura 13.4.1 (but probably sufficient to be using older OS's)
M1 arm64 architecture

> What compilers/modules are you using?

Clang 14.0.3
GNU Fortran 12.2.0
spack-stack 1.4.0

> Steps to reproduce the behavior

1. git clone https:://github.com/jcsda-internal/ioda-bundle
2. Build ioda-bundle with develop branches and default ecbuild settings
3. ctest

## Expected behavior

All iodaconv tests pass

**Comment by BenjaminRuston** [comment]
this is redundant with another issue and has been resolved

**Comment by srherbener** [comment]
@BenjaminRuston I just tested all develop branches using ioda-bundle on my Mac, arm64 (as noted above) and I'm still seeing these test failures.

What is the other issue that this is a duplicate? Perhaps I'm missing something that is explained in the other issue. Otherwise, I'd like to re-open this issue. Thanks!
